name: sport_analytics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - yaml
  - sqlalchemy
  - psycopg2-binary
  - pandas
  - numpy
  - matplotlib
  - pyyaml
  - requests